name: eval
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - numpy=1.24.4
  - pip=24.2
  - python=3.8.19
  - pytorch=2.4.0=py3.8_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8
  - scipy=1.10.1
  - torchaudio=2.4.0=py38_cu118
  - torchvision=0.19.0=py38_cu118
  - pip:
    - monai==1.3.2
    - monai-generative==0.2.3
    - nibabel==5.2.1
    - tqdm==4.66.5
